book_review/config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :reviews, except: [:show, :index]
    resources :favorite_books, only: [:create, :destroy]
    resources :comments, except: [:show, :index]
  end
  root "static_pages#show", page: "home"
  get "/static_pages/*page", to: "static_pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
   
 resources :relationships, only: [:index, :create, :destroy]
  namespace :admin do
    resources :categories, except: [:show]
    resources :books
    resources :requests, only: [:index, :update]
  end

  resources :users, only: [:index, :show, :destroy]
  resources :requests, except: [:edit, :update, :show]
end

book_review/app/views/layouts/_footer.html.erb
<footer class="footer">

  <p class="infor"> <%= link_to t("layout.base_title"), root_path %> </p>
  <small>
    <p class="infor">
      &copy; <%= Date.today %> <%= t "layout.framgia" %> <br>
      <%= t "layout.address" %> <br>
      <%= t "layout.phone" %> <%= t "layout.phone-number" %> <br>
    </p>
  </small>
</footer>

book_review/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse header-pages">
  <div class="container">
    <%= link_to t("layout.base_title"), root_path , class: "logo" %>
    <nav>
      <ul class="nav nav-list navbar-right">
        <li class="nav-item"><%= link_to t("layout.home"), root_path, 
          class: "nav-item-home" %></li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to t(".users"), users_path, 
            class: "nav-item-home" %></li>
          <% if current_user.is_admin? %>
            <li class="nav-item"><%= link_to t(".request"), admin_requests_path %></li>
            <li class="nav-item"><%= link_to t(".all_book"), admin_books_path %></li>
            <li class="nav-item" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t "layout.category" %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t(".new"), new_admin_category_path %></li>
                <li class="divider"></li>
                <li><%= link_to t(".all_category"), admin_categories_path %></li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item"><%= link_to t("request"), requests_path %></li>
          <% end %>
          <li class="nav-item" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "layout.header.account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("layout.header.profile"), current_user %></li>
              <li><%= link_to t("layout.header.setting"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("layout.header.logout"), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to t("layout.log-in"), login_path %></li>
          <li class="nav-item"><%= link_to t("layout.sign-up"), 
            signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

book_review/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

book_review/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>