book_review/config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :reviews, except: [:show, :index]
    resources :favorite_books, only: [:create, :destroy]
    resources :comments, except: [:show, :index]
  end
  root "static_pages#show", page: "home"
  get "/static_pages/*page", to: "static_pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
   
 resources :relationships, only: [:index, :create, :destroy]
  namespace :admin do
    resources :categories, except: [:show]
    resources :books
    resources :requests, only: [:index, :update]
  end

  resources :users, only: [:index, :show, :destroy]
  resources :requests, except: [:edit, :update, :show]
end

book_review/app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
  
  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

book_review/app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :load_category, only: [:edit, :update, :destroy]
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "controller.categories.create"
      redirect_to admin_categories_path
    else
      render :new
    end
  end
  
  def edit 
  end 
  
  def update
    if @category.update_attributes category_params
      flash[:success] = t "controller.categories.update"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end
 
  def destroy
    @category.destroy
    flash[:success] = t "controller.categories.delete"
    redirect_to admin_categories_path
  end
 
  private
  def load_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t "controller.categories.found"
      redirect_to root_path
    end
  end

  def category_params
    params.require(:category).permit :name
  end
 end

book_review/app/views/admin/categories/edit.html.erb
<% provide :title, t("layout.categories.edit") %>
<h1><%= t "layout.categories.h1" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @category, url: admin_category_path do |f| %>
      <%= render "shared/error_messages", target: @category %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.submit t("layout.categories.save"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

book_review/app/views/admin/categories/index.html.erb
<% provide :title, t("layout.categories.all") %>
<h1><%= t "layout.categories.all" %></h1>
  <ul class= "category">
    <% @categories.each do |category| %>
      <li class="col-md-12">
       <div id= "category", class="col-md-8"><%= category.name %> </div>
       <div class="col-md-1"><%= link_to t("layout.categories.btn_edit"),
         edit_admin_category_path(category), class: "btn btn-info" %></div>
       <div class="col-md-1"><%= link_to t("layout.categories.btn_delete"), 
         admin_category_path(category),method: :delete, 
         data: {confirm: t("layout.msg_del")}, 
         class: "btn btn-danger" %></div>
      </li>
    <% end %>
  </ul>

book_review/app/views/admin/categories/new.html.erb
<% provide :title, t("layout.category") %>
<h1><%= t "layout.category" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @category, url: admin_categories_path do |f| %>
      <%= render "shared/error_messages", target: @category %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.submit t("layout.categories.new"), 
        class: "btn btn-primary" %>
    <% end %>
  </div>
</div>