book_review/config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :reviews, except: [:show, :index]
    resources :favorite_books, only: [:create, :destroy]
    resources :comments, except: [:show, :index]
  end
  root "static_pages#show", page: "home"
  get "/static_pages/*page", to: "static_pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
   
 resources :relationships, only: [:index, :create, :destroy]
  namespace :admin do
    resources :categories, except: [:show]
    resources :books
    resources :requests, only: [:index, :update]
  end

  resources :users, only: [:index, :show, :destroy]
  resources :requests, except: [:edit, :update, :show]
end

book_review/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  
  has_many :reviews, dependent: :destroy
  has_many :statuses, dependent: :destroy

  has_many :favorite_books, dependent: :destroy

  mount_uploader :image, ImageUploader

  scope :search_by, ->search {where "title LIKE ? OR author LIKE ?",
    "%#{search}%", "%#{search}%"}
  scope :search_by_title, ->search_title {where "title LIKE ?",
    "%#{search_title}%"}
  
  validates :image, presence: true
  validates :title, presence: true
  validates :author, presence: true
  validates :number_page, presence: true, numericality: true
  validates :publish_date, presence: true
  validates :category, presence: true
end

book_review/app/models/supports/book.rb
class Supports::Book
  attr_reader :book

  def initialize book
    @book = book
  end

  def categories
    @categories = Category.all
  end

  def category name
    @category = Category.find_by name: name
  end

  def avarge_rate reviews
    sum = 0
    if reviews.any?
      reviews.each do |review|
        sum += review.rate
      end
      sum.to_f / reviews.count
    else
      0
    end
  end
end

book_review/app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :load_book, except: [:index, :new, :create]
  before_action :load_categories, except: [:index, :show, :destroy]

  def index
    @books = Book.search_by_title(params[:search]).paginate page: params[:page]
  end

  def new
    @book = Book.new
  end
	
  def create
    @book = Book.new book_params
    if @book.save
      flash.now[:success] = t "controllers.admin.books.create"
      redirect_to admin_book_path @book
    else
      flash.now[:danger] = t "controllers.admin.books.not_new"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @book.update_attributes book_params
      flash.now[:success] = t "controllers.admin.books.update"
      redirect_to admin_books_path
    else
      flash.now[:danger] = t "controllers.admin.books.not_update"
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to admin_books_path
  end
    
  private
  def load_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash.now[:danger] = t "controllers.admin.books.not_found"
      redirect_to admin_books_path
    end
  end
  
  def load_categories
    @categories = Category.all.map{|category| [category.name, category.id]}
    unless @categories
      flash.now[:danger] = t "controllers.admin.books.not_found_category"
      redirect_to admin_books_path
    end
  end

  def book_params
    params.require(:book).permit :title, :description, 
      :author, :category_id, :image, :number_page, :publish_date
  end
end

book_review/app/controllers/book_controller.rb
class BookController < ApplicationController
  before_action :find_book, only: [:show]
  def index
    @supports = Supports::Book.new @book
    @books = @supports.category(params[:category]).nil? ? 
      Book.all : @supports.category(params[:category]).books
    if params[:category] && @supports.category(params[:category]).nil?
      flash[:warning] = t "not_category"
      redirect_to book_index_path
    end
  end

  def show
  end

  private
  def book_params
    params.require(:book).permit :title, :author, :images, :category_id
  end
  def find_book
    @book = Book.find_by id: params[:id]
    if @book.nil?
      flash[:warning] = t("controller.book.not_found_book")
      redirect_to book_index_path
    end
  end
end

book_review/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show]
  before_action :find_favorite, only: [:show]
  
  def index
    @supports = Supports::Book.new @book
    category = @supports.category params[:category]
    @books = (category.nil? ? Book.search_by(params[:search]) : 
      category.books).paginate(page: params[:page])
    if params[:category] && @supports.category(params[:category]).nil?
      flash[:warning] = t "not_category"
      redirect_to books_path
    end
  end

  def show
    @supports = Supports::Book.new @book
  end

  private
  def book_params
    params.require(:book).permit :title, :author, :images, :category_id
  end

  def find_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:warning] = t("controller.book.not_found_book")
      redirect_to books_path
    end
  end
  
  def find_favorite
    @favorite = current_user.favorite_books.find_by book_id: @book.id
  end
end

book_review/app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book], html: {multipart: true} do |f| %>
  <%= render "shared/error_messages", target: @book %>
  <%= f.label :category %>
  <%= f.select :category_id, @categories, prompt: t(".category") %>
  
  <%= f.label :image %>
  <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png",
    class: "upload-image" %>
  
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.label :author %>
  <%= f.text_field :author, class: "form-control" %>

  <%= f.label :number_page %>
  <%= f.number_field :number_page, class: "form-control" %>
  
  <%= f.label :publish_date %>
  <%= f.date_field :publish_date, class: "form-control" %>
  
  <%= f.submit t(".save"), class: "btn btn-primary" %>
<% end %>

book_review/app/views/admin/books/_list_book.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table table-bordered table_request">
      <thead>
        <tr class="info">
          <th class="center col-md-7"><%= t".title" %></th>
          <th class="center col-md-2"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td class ="center">  
              <%= link_to book.title, admin_book_path(book) %>
            </td>
            <td>
              <%= link_to t(".edit"),
                edit_admin_book_path(book), class: "btn btn-info" %>
              <%= link_to t(".delete"), 
                admin_book_path(book), method: :delete, 
                data: {confirm: t(".confirm")}, 
                class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

book_review/app/views/admin/books/edit.html.erb
<% provide :title, t(".new_book") %>
<h1><%= t ".new_book" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

book_review/app/views/admin/books/index.html.erb
<% provide :title, t(".all") %>
<h1><%= t ".all" %></h1>
  <div class="container" >
    <div class="row">
      <%= form_tag admin_books_path, remote: true, method: :get do %>
        <span class="center col-md-3 col-md-offset-1" >
          <%= text_field_tag :search, params[:search],
            placeholder: t(".search"), class: "form-control" %>
        </span>
        <span class=" col-md-1" >
          <%= submit_tag t(".btn_search"), class: "btn btn-primary" %>
        </span>
      <% end %>
      <span class=" col-md-4"></span>
      <span class=" col-md-2">
        <%= link_to t(".new"), new_admin_book_path, class: "btn btn-primary" %>
      </span>
    </div>
  </div>
  <div class="books">
    <%= render "list_book" %>
  </div>

        

book_review/app/views/admin/books/index.js.erb
$('.books').html('<%= j render "list_book" %>');

book_review/app/views/admin/books/new.html.erb
<% provide :title, t("new_book") %>
<h1><%= t ".new_book" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

book_review/app/views/admin/books/show.html.erb
<div class= "row">
  <div class="col-md-12">
    <div class="col-md-4 ">
      <%= image_tag @book.image.url if @book.image? %>
    </div>
    <div class="col-md-7 ">
      <h1><%= @book.title %></h1>
      <h3><%= t ".author" %><%= @book.author %></h3>
      <h3><%= t ".number_page" %><%= @book.number_page %></h3>
      <h3><%= t ".publish_date" %><%= l @book.publish_date %></h3>
      <h3><%= t ".category" %><%= @book.category.name %></h3>
      <p><%= t ".description" %><%= @book.description %></p>
    </div>
  </div>
</div>