book_review/config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :reviews, except: [:show, :index]
    resources :favorite_books, only: [:create, :destroy]
    resources :comments, except: [:show, :index]
  end
  root "static_pages#show", page: "home"
  get "/static_pages/*page", to: "static_pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
   
 resources :relationships, only: [:index, :create, :destroy]
  namespace :admin do
    resources :categories, except: [:show]
    resources :books
    resources :requests, only: [:index, :update]
  end

  resources :users, only: [:index, :show, :destroy]
  resources :requests, except: [:edit, :update, :show]
end

book_review/app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "shared.contains" %><%= pluralize target.errors.count,
        t("shared.error") %>.
    </div>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

book_review/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to relationships_path user_id: @user.id, 
    relation: "following" do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t ".following" %>
  <% end %>
  <%= link_to relationships_path user_id: @user.id, 
    relation: "followers" do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t ".followers" %>
  <% end %>
</div>